#!/usr/bin/env bash
# Build .env.render from .env — production keys only (for Render dashboard / CLI).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="${1:-$ROOT/.env}"
OUTPUT="${2:-$ROOT/.env.render}"

if [ ! -f "$SOURCE" ]; then
  echo "Missing $SOURCE — copy .env.example to .env first."
  exit 1
fi

# Keys pushed to Render (secrets + production overrides).
PRODUCTION_KEYS=(
  OPENAI_API_KEY
  LLM_MODEL
  ELEVENLABS_API_KEY
  ELEVENLABS_VOICE_ID
  ELEVENLABS_MODEL
  LIBRARY_CDN_URL
  R2_BUCKET
  R2_ENDPOINT
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  DEFAULT_GENRE
  MIN_LIBRARY_PER_GENRE
  AVOID_REPLAY_LIMIT
  CROSSFADE_SEC
  MIN_TRACKS_BEFORE_DJ
  DJ_MIN_INTERVAL_SEC
  DJ_PREP_LEAD_SEC
  YOUTUBE_CLIENT_ID
  YOUTUBE_CLIENT_SECRET
  YOUTUBE_REFRESH_TOKEN
  YOUTUBE_BROADCAST_ID
  YOUTUBE_VIDEO_ID
  YOUTUBE_RTMP_URL
  YOUTUBE_STREAM_KEY
  YOUTUBE_API_KEY
  CHAT_PROVIDER
  CHAT_POLL_INTERVAL_MS
  CHAT_WINDOW_MS
  ADMIN_API_KEY
  BROADCAST_STALE_SEC
)

get_var() {
  local key="$1"
  grep -E "^${key}=" "$SOURCE" 2>/dev/null | tail -1 | cut -d= -f2- || true
}

{
  echo "# Generated by scripts/build-render-env.sh — do not commit"
  echo "# Paste into Render dashboard or use with deploy script"
  echo ""
  for key in "${PRODUCTION_KEYS[@]}"; do
    value="$(get_var "$key")"
    if [ -n "$value" ]; then
      printf '%s=%s\n' "$key" "$value"
    fi
  done
} > "$OUTPUT"

# Production overrides
if grep -q '^CHAT_PROVIDER=' "$OUTPUT"; then
  sed -i '' 's/^CHAT_PROVIDER=.*/CHAT_PROVIDER=youtube/' "$OUTPUT" 2>/dev/null || \
    sed -i 's/^CHAT_PROVIDER=.*/CHAT_PROVIDER=youtube/' "$OUTPUT"
else
  echo "CHAT_PROVIDER=youtube" >> "$OUTPUT"
fi

if grep -q '^MIN_LIBRARY_PER_GENRE=' "$OUTPUT"; then
  sed -i '' 's/^MIN_LIBRARY_PER_GENRE=.*/MIN_LIBRARY_PER_GENRE=1/' "$OUTPUT" 2>/dev/null || \
    sed -i 's/^MIN_LIBRARY_PER_GENRE=.*/MIN_LIBRARY_PER_GENRE=1/' "$OUTPUT"
fi

echo "Wrote $OUTPUT ($(grep -cE '^[A-Z_]+=' "$OUTPUT" || true) vars with values)"
